defaults: &defaults
  working_directory: /circleci
  docker:
    - image: docker:17.06.0-ce-git

version: 2

jobs:
  01_build_image:
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run:
          name: Build Docker image
          command: |
            set -ex
            docker build -t circleci .

  02_test_image:
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - run:
          name: Check if dependecies are installed
          command: |
            set -ex
            docker run circleci bash -c 'which docker'
            docker run circleci bash -c 'which docker-compose'
            docker run circleci bash -c 'which ci'
            docker run circleci bash -c 'which python'
            docker run circleci bash -c 'which wfi'

workflows:
  version: 2
  test:
    jobs:
      - 01_build_image
      - 02_test_image:
          requires:
            - 01_build_image
