defaults: &defaults
  working_directory: /circleci
  docker:
    - image: docker:17.06.0-ce-git

version: 2

jobs:
  01_run_ci:
    <<: *defaults

    steps:
      - setup_remote_docker:
          reusable: true

      - checkout

      - run:
          name: Build Docker image
          command: |
            set -ex
            docker build -t circleci:$(cat VERSION) .

      - run:
          name: Check if dependecies are installed
          command: |
            set -ex
            which docker
            which docker-compose
            which ci
            which python
            which wfi

workflows:
  version: 2
  test:
    jobs:
      - 01_run_ci
